module.exports = [
  {
    id: 1,
    name: 'Plain White Plate',
    price: 25.0,
    quantity: 100,
    imageURL: '../../plates/white.png',
    description: 'Classic round white dining plate.',
  },
  {
    id: 2,
    name: 'Golden Plate',
    price: 55.0,
    quantity: 100,
    imageURL: '../../plates/gold.png',
    description: 'Royal gold dining and display plate.',
  },
  {
    id: 3,
    name: 'Royal Designed Plate',
    price: 1000.0,
    quantity: 100,
    imageURL: '../../plates/royal.png',
    description: 'Royal design display plate.',
  },
  {
    id: 4,
    name: 'Terracotta Plate',
    price: 55.0,
    quantity: 100,
    imageURL: '../../plates/terracotta.png',
    description: 'Terracotta dining plate, red hue.',
  },
  {
    id: 5,
    name: 'Blue Vine Plate',
    price: 25.0,
    quantity: 100,
    imageURL: '../../plates/ceramic.png',
    description: 'Blue garden vine dining plate.',
  },
  {
    id: 6,
    name: 'Lime Green Plate',
    price: 25.0,
    quantity: 100,
    imageURL: '../../plates/lime.png',
    description: 'Lime green dining plate.',
  },
  {
    id: 7,
    name: 'Textured Black Plate',
    price: 55.0,
    quantity: 100,
    imageURL: '../../plates/blackshine.png',
    description: 'Sleek textured black dining plate.',
  },
  {
    id: 8,
    name: 'Smooth Black Plate',
    price: 25.0,
    quantity: 100,
    imageURL: '../../plates/matteblack.png',
    description: 'Smooth porcelain black dining plate.',
  },
  {
    id: 9,
    name: 'Elegant Cream Colored Plate',
    price: 55.0,
    quantity: 100,
    imageURL: '../../plates/victorian.png',
    description: 'Classic elegant creamy colored dining plate.',
  },
]
